
* vc-next-action

Subject: Re: In defense of VC [was: In support of Jonas Bernoulli's Magit]
Date: Sun, 16 Jul 2017
> If multiple files are modified, the “next action” could be to display
> the ‘vc-dir’ buffer for the current repository.

We had an argument about changing `M-x vc-dir' to show the repository root
right away, instead of prompting. Couldn't reach an agreement.
So I doubt your suggestion would be accepted as the default workflow.

> in the unlikely case the asking behavior is needed, it could be
> triggered by giving a prefix argument.)

See https://debbugs.gnu.org/cgi/bugreport.cgi?bug=12492#23
There was also a discussion on emacs-devel quite a bit later
and f302475471df0553b3ee442112981f9b146e0b55

TODO: C-x v V should deduce all changed files

** Example

#+begin_src emacs-lisp :results none
(with-temp-buffer
  (vc-call-backend
   (vc-responsible-backend default-directory) 'dir-status-files default-directory nil
   (lambda (entries &optional more-to-come)
     (message "! %S" entries))))
#+end_src

* vc-dir

Now, vc-dir seems similar to magit-status.  But it has one _huge_
drawback: it requires me to press RET each time after I invoke it.  (Why
would I want to invoke vc-dir for some other directory than the one I'm
in anyway?  And in such rare cases, C-u would handle that much better.)

** Problem

Typing 'v' (vc-next-action) at the beginning of *vc-dir* buffer signals the error
"When applying VC operations to multiple files, the files are required
to be in similar VC states.  File in state edited clashes with state unregistered.
